### ISSUE TITLE
User can log training sessions

### ISSUE THREAD

**Issue by ryan-byrnes** [ryan-byrnes/Final-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can input their current, past, and/or future training sessions

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click on a date and enter information about their training program for that day.  They can input exercise names, sets, repetitions, and training weight.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-07 at 10 19 41 AM](https://user-images.githubusercontent.com/20606439/132385525-1e5f0219-691a-492a-a898-5e1c7b742e6e.png)

![Screen Shot 2021-09-07 at 10 20 46 AM](https://user-images.githubusercontent.com/20606439/132385614-08d04df0-b37a-4079-a750-9524a89b6f70.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create post route allowing user to input training data to the database
- [x] Test POST route with HTTPie

### ⚡ Client

- [x] Create nav bar component
- [x] Add date picker to training session component page
- [x] Create training session component
- [x] create modal component for user to add exercise
- [x] Test to make sure entries are displayed on the training sessions page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
