### ISSUE TITLE
User can view training sessions

### ISSUE THREAD

**Issue by ryan-byrnes** [ryan-byrnes/Final-Project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view any of his/her logged training sessions.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click on the calendar icon and choose a date he/she would like to view.  Once chosen, user will be able to view the training session for that date.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-07 at 10 28 05 AM](https://user-images.githubusercontent.com/20606439/132386528-00e5a7f5-30fe-42ed-9d8c-36eb979e3057.png)

![Screen Shot 2021-09-07 at 10 28 17 AM](https://user-images.githubusercontent.com/20606439/132386536-9b2a4887-2e24-4b22-8218-a5a9fd6ef7a0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create GET route that will sent training session data as a response

### ⚡ Client

- [x] Create fetch GET request to receive training session data
- [x] Create exercise list component
- [x] Use CSS to style exercise list

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
