### ISSUE TITLE
User can input personal records (PR's)

### ISSUE THREAD

**Issue by ryan-byrnes** [ryan-byrnes/Final-Project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can input/edit personal records.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the "PR's" menu item and then view, edit, or add new personal records by clicking the "Add PR" link.  After clicking "Add PR", user may select an exercise and input weight and number of reps.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-07 at 10 33 02 AM](https://user-images.githubusercontent.com/20606439/132387119-9565a6a2-b261-4877-ad82-9cfc6824b953.png)

![Screen Shot 2021-09-07 at 10 33 52 AM](https://user-images.githubusercontent.com/20606439/132387131-eff9e08e-03e7-4b16-8575-142543bb40e6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update data.sql to include exercises in the "exerciseList" table that can be used to test new PR inputs

### ☁️ Server

- [x] Create server directory
- [x] Create index.js within server directory
- [x] install new package.json
- [x] install express dependency
- [x] Create a server listening on port 3000 to test server code
- [x] Create a POST route for the user to upload new PR data to the PR table in the db
- [x] Test with HTTPie
- [x] Create a PUT route that will allow the user to edit existing PR data
- [x] Test with HTTPie
- [x] Create a GET route that will allow user to see PR data
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Install react and react-dom as dependencies
- [x] Install webpack, webpack-cli, babel-loader, @babel/core, @babel/plugin-transform-react-jsx as dev dependencies
- [x] Add build script to package.json
- [x] Create webpack.config.js file and add appropriate config code
- [x] Create index.jsx and pr.jsx files
- [x] Create a component for the PR's page view
- [x] Create an "Add PR" button component
- [x] Create a modal component where the user will input PR data
- [x] Create a search bar component to search for and add exercises
- [x] Create an exercise list component
- [x] Create a submit button component
- [x] Create a modal close button component
- [x] Create nav bar header and footer
- [x] Add/edit CSS to match figma design

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
