### ISSUE TITLE
User can view progress tracking graphs

### ISSUE THREAD

**Issue by ryan-byrnes** [ryan-byrnes/Final-Project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view total training volume and PR progress graphs.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

By clicking on the "Analytics" menu item, the user will be able to view a graphical representation of their training volume and PR's.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-07 at 10 41 08 AM](https://user-images.githubusercontent.com/20606439/132388053-e1d41f61-89f4-4334-ab71-a0b4604312d7.png)

![Screen Shot 2021-09-07 at 10 41 46 AM](https://user-images.githubusercontent.com/20606439/132388063-e212e3a9-89bd-4df9-9eaf-11d02b4c5741.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create get route that will send training log data as a response
- [x] Create get request that will send PR data as a response

### ⚡ Client

- [x] Create Analytics page component
- [x] Install re-charts
- [x] create fetch request to retrieve tonnage data
- [x] create fetch request to retrieve pr data
- [x] prepare data to use in charts
- [x] create chart components for tonnage and PR's

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
